export const BUNDLE_TITLE_MAX_LENGTH = 50;
export const BUNDLE_DESCRIPTION_MAX_LENGTH = 200;

export const ACTION_SLOT_SIZE = 36;
export const ACTION_SLOT_BUTTON_SIZE = 28;
export const ACTION_SLOT_BUTTON_BORDER_RADIUS = 100;
export const ACTION_SLOT_BUTTON_ICON_SIZE = 14;
export const ACTION_SLOT_DISABLED_OPACITY = 0.4;

export const BUNDLE_CREATOR_INFO_AVATAR_SIZE = 22;
export const BUNDLE_CREATOR_INFO_TEXT_LINE_HEIGHT = 16;
export const BUNDLE_CREATOR_AVATAR_FALLBACK_ICON_SIZE = 14;
