export const BUNDLE_TITLE_MAX_LENGTH = 50;
export const BUNDLE_DESCRIPTION_MAX_LENGTH = 200;

export const ACTION_SLOT_SIZE = 36;

export const BUNDLE_CREATOR_INFO_AVATAR_SIZE = 22;
export const BUNDLE_CREATOR_INFO_TEXT_LINE_HEIGHT = 16;
export const BUNDLE_CREATOR_AVATAR_FALLBACK_ICON_SIZE = 14;
